name: Build Android

env:
  path: android
  module: app
  bundle_id: jd.boiv.in.test

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains'
          java-version: '21'

      - name: Change wrapper permissions
        working-directory: ${{ env.path }}
        run: chmod +x ./gradlew

      # Change bundle id for easy testing of this workflow when used as a template
      - name: Change bundle id
        working-directory: ${{ env.path }}/${{ env.module }}
        run: |
          sed -i -E "s/applicationId = \"jd.boiv.in.test\"/applicationId = \"${{ env.bundle_id }}\"/" build.gradle.kts

      #- name: Build APK
      #  working-directory: ${{ env.path }}
      #  run: ./gradlew assembleRelease

      - name: Build AAB
        working-directory: ${{ env.path }}
        run: ./gradlew bundleRelease

      - name: Rename files
        run: |
          mkdir build
          find "${{ env.path }}/${{ env.module }}/build/outputs/bundle/release" -name '*.aab' -exec mv '{}' build/android.aab \;

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-android
          path: build