name: Build Android

env:
  path: android
  module: app

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains'
          java-version: '21'

      - name: Change wrapper permissions
        working-directory: ${{ env.path }}
        run: chmod +x ./gradlew

      #- name: Build gradle project
      #  working-directory: ${{ env.path }}
      #  run: ./gradlew build

      #- name: Build APK
      #  working-directory: ${{ env.path }}
      #  run: ./gradlew assembleRelease

      - name: Build AAB
        working-directory: ${{ env.path }}
        run: ./gradlew bundleRelease

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-android
          path: ${{ env.path }}/${{ env.module }}/build/outputs/bundle/release/