name: Build Android

env:
  ANDROID_PACKAGE_NAME: ${{ secrets.ANDROID_PACKAGE_NAME }}
  ANDROID_KEYSTORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASS }}

on:
  workflow_call:
    inputs:
      path:
        required: true
        default: 'android'
        type: string
      module:
        required: true
        default: 'app'
        type: string
      java-version:
        default: '21'
        type: string
      distribution:
        default: 'jetbrains'
        type: string
      apk-only:
        default: false
        type: boolean

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: '${{ inputs.distribution }}'
          java-version: '${{ inputs.java-version }}'

      - name: Change wrapper permissions
        working-directory: ${{ inputs.path }}
        run: chmod +x ./gradlew

      # Change package name for easy testing of this workflow when used as a template
      - name: Change package name
        if: ${{ env.ANDROID_PACKAGE_NAME != '' }}
        continue-on-error: true
        working-directory: ${{ inputs.path }}/${{ inputs.module }}
        run: |
          sed -i -E "s/applicationId = \"jd.boiv.in.test\"/applicationId = \"${{ secrets.ANDROID_PACKAGE_NAME }}\"/" build.gradle.kts

      - name: Build APK
        if: ${{ inputs.apk-only }}
        working-directory: ${{ inputs.path }}
        run: ./gradlew assembleRelease

      - name: Rename files APK
        if: ${{ inputs.apk-only }}
        run: |
          mkdir build
          find "${{ inputs.path }}/${{ inputs.module }}/build/outputs/apk/release" -name '*.apk' -exec mv '{}' build/android.apk \;

      - name: Build AAB
        if: ${{ !inputs.apk-only }}
        working-directory: ${{ inputs.path }}
        run: ./gradlew bundleRelease
      
      - name: Rename files AAB
        if: ${{ !inputs.apk-only }}
        run: |
          mkdir build
          find "${{ inputs.path }}/${{ inputs.module }}/build/outputs/bundle/release" -name '*.aab' -exec mv '{}' build/android.aab \;

      - name: Save .keystore
        if: ${{ env.ANDROID_KEYSTORE_PASS != '' }}
        working-directory: build
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > .keystore

      # Convert PKCS12 keystore to JKS (if possible)
      - name: Convert keystore
        continue-on-error: true
        if: ${{ env.ANDROID_KEYSTORE_PASS != '' }}
        working-directory: build
        run: |
          keytool -importkeystore -srckeystore .keystore -destkeystore keystore.jks -srcstoretype PKCS12 \
          -deststoretype jks -srcstorepass ${{ secrets.ANDROID_KEYSTORE_PASS }} -deststorepass ${{ secrets.ANDROID_KEYSTORE_PASS }} \
          -srcalias ${{ secrets.ANDROID_KEYALIAS_NAME }} -destalias ${{ secrets.ANDROID_KEYALIAS_NAME }} \
          -srckeypass ${{ secrets.ANDROID_KEYALIAS_PASS }} -destkeypass ${{ secrets.ANDROID_KEYALIAS_PASS }}
          rm .keystore
          mv keystore.jks .keystore

      - name: Unsign AAB
        if: ${{ env.ANDROID_KEYSTORE_PASS != '' && !inputs.apk-only }}
        continue-on-error: true
        working-directory: build
        run: |
          zip -d android.aab META-INF/\*
          
      - name: Unsign APK
        if: ${{ env.ANDROID_KEYSTORE_PASS != '' && inputs.apk-only }}
        continue-on-error: true
        working-directory: build
        run: |
          zip -d android.apk META-INF/\*

      - name: Sign AAB
        if: ${{ env.ANDROID_KEYSTORE_PASS != '' && !inputs.apk-only }}
        working-directory: build
        run: |
          jarsigner -sigalg SHA256withRSA -digestalg SHA-256 \
          -keystore .keystore -storepass "${{ secrets.ANDROID_KEYSTORE_PASS }}" -keypass "${{ secrets.ANDROID_KEYALIAS_PASS }}" \
          "android.aab" "${{ secrets.ANDROID_KEYALIAS_NAME }}"

      # Download bundletool to generate a .APK from the .AAB for external distribution
      - name: Generate .APK (signed)
        if: ${{ env.ANDROID_KEYSTORE_PASS != '' && !inputs.apk-only }}
        working-directory: build
        run: |
          json=$(curl -s https://api.github.com/repos/google/bundletool/releases/latest)
          downloadUrl=$(echo $json | jq -r ".assets | .[].browser_download_url")
          curl $downloadUrl -4 -sL -o 'bundletool.jar'

          java -jar bundletool.jar build-apks --bundle=android.aab --output=android.apks \
          --mode=universal \
          --ks=.keystore \
          --ks-pass="pass:${{ secrets.ANDROID_KEYALIAS_PASS }}" \
          --ks-key-alias=${{ secrets.ANDROID_KEYALIAS_NAME }} \
          --key-pass="pass:${{ secrets.ANDROID_KEYSTORE_PASS }}"

          unzip -p android.apks universal.apk > android.apk

          rm android.apks
          rm bundletool.jar

      - name: Sign APK
        if: ${{ env.ANDROID_KEYSTORE_PASS != '' }}
        working-directory: build
        run: |
          jarsigner -sigalg SHA256withRSA -digestalg SHA-256 \
          -keystore .keystore -storepass "${{ secrets.ANDROID_KEYSTORE_PASS }}" -keypass "${{ secrets.ANDROID_KEYALIAS_PASS }}" \
          "android.apk" "${{ secrets.ANDROID_KEYALIAS_NAME }}"

      - name: Generate .APK (unsigned)
        if: ${{ env.ANDROID_KEYSTORE_PASS == '' && !inputs.apk-only }}
        working-directory: build
        run: |
          json=$(curl -s https://api.github.com/repos/google/bundletool/releases/latest)
          downloadUrl=$(echo $json | jq -r ".assets | .[].browser_download_url")
          curl $downloadUrl -4 -sL -o 'bundletool.jar'

          java -jar bundletool.jar build-apks --bundle=android.aab --output=android.apks --mode=universal

          unzip -p android.apks universal.apk > android.apk
          rm android.apks
          rm bundletool.jar

      - name: Cleanup
        working-directory: build
        run: |
          rm -f .keystore

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-android
          path: build