name: Generate .keystore

# Github Action do not support secure inputs for now
# See: https://github.com/orgs/community/discussions/12764
# So instead, add those two secrets to your github repository: ANDROID_KEYALIAS_PASS / ANDROID_KEYSTORE_PASS
# Then you can download the artifact and makes sure to delete it! Not recommended for public repo!
# This is mostly added as an example on how you can generate the .keystore without using a GUI.
on:
  workflow_dispatch:
    inputs:
      alias:
        type: string
        description: Alias (anything you want)
      #password:
      #  type: password
      #  description: Password
      name:
        type: string
        description: Your Name
      organization:
        type: string
        description: Organization Name
      locality:
        type: string
        description: Locality / City
      state:
        type: string
        description: State / Province
      country:
        type: string
        description: Country (2 letter code)
  workflow_call:
    inputs:
      alias:
        required: true
        type: string
      #password:
      #  required: true
      #  type: password
      name:
        required: true
        type: string
      organization:
        required: true
        type: string
      locality:
        required: true
        type: string
      state:
        required: true
        type: string
      country:
        required: true
        type: string
  

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains'
          java-version: '21'

      - name: Create .keystore (PKCS12)
        run: |
          mkdir build
          cd build
          keytool -genkey -v -keystore .keystore -alias ${{ inputs.alias }} -keyalg RSA -keysize 2048 \
          -dname "CN=${{ inputs.name }}, O=${{ inputs.organization }}, L=${{ inputs.locality }}, S=${{ inputs.state }}, C=${{ inputs.country }}" \
          -validity 10000 -keypass "${{ secrets.ANDROID_KEYALIAS_PASS }}" -storepass "${{ secrets.ANDROID_KEYSTORE_PASS }}" -noprompt

      - name: Create .keystore (JKS)
        working-directory: build
        run: |
          keytool -importkeystore -srckeystore .keystore -destkeystore keystore.jks -srcstoretype PKCS12 \
          -deststoretype jks -srcstorepass "${{ secrets.ANDROID_KEYSTORE_PASS }}" -deststorepass "${{ secrets.ANDROID_KEYSTORE_PASS }}" \
          -srcalias ${{ inputs.alias }} -destalias ${{ inputs.alias }} \
          -srckeypass "${{ secrets.ANDROID_KEYALIAS_PASS }}" -destkeypass "${{ secrets.ANDROID_KEYALIAS_PASS }}"

      - name: Base64
        working-directory: build
        run: |
          base64 .keystore >> base64_PKCS12.txt
          base64 keystore.jks >> base64_JKS.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: keystore
          path: build
          include-hidden-files: true