name: Generate .keystore

on:
  workflow_dispatch:
    inputs:
      alias:
        type: string
        description: Alias
      password:
        type: string
        description: Password
      name:
        type: string
        description: Name
      organization:
        type: string
        description: Organization
      locality:
        type: string
        description: Locality
      state:
        type: string
        description: State
      country:
        type: string
        description: Country (2 letter code)

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains'
          java-version: '21'

      - name: Create .keystore (PKCS12)
        run: |
          mkdir build
          cd build
          keytool -genkey -v -keystore .keystore -alias ${{ inputs.alias }} -keyalg RSA -keysize 2048 \
          -dname "CN=${{ inputs.name }}, O=${{ inputs.organization }}, L=${{ inputs.locality }}, S=${{ inputs.state }}, C=${{ inputs.country }}" \
          -validity 10000 -keypass ${{ inputs.password }} -storepass ${{ inputs.password }} -noprompt

      - name: Create .keystore (JKS)
        working-directory: build
        run: |
          keytool -importkeystore -srckeystore .keystore -destkeystore keystore.jks -srcstoretype PKCS12 \
          -deststoretype jks -srcstorepass ${{ inputs.password }} -deststorepass ${{ inputs.password }} \
          -srcalias ${{ inputs.alias }} -destalias ${{ inputs.alias }} \
          -srckeypass ${{ inputs.password }} -destkeypass ${{ inputs.password }}

      - name: Base64
        working-directory: build
        run: |
          base64 .keystore >> base64.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: keystore
          path: build
          include-hidden-files: true